// <auto-generated />
using AngularTutSiteApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AngularTutSiteApi.Migrations
{
    [DbContext(typeof(CurdSnackContext))]
    partial class CurdSnackContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AngularTutSiteApi.Entities.CurdSnack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DetailForeignKey");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("CurdSnack");
                });

            modelBuilder.Entity("AngularTutSiteApi.Entities.CurdSnackDetail", b =>
                {
                    b.Property<long>("Id");

                    b.Property<string>("Details");

                    b.HasKey("Id");

                    b.ToTable("CurdSnackDetail");
                });

            modelBuilder.Entity("AngularTutSiteApi.Entities.CurdSnackDetail", b =>
                {
                    b.HasOne("AngularTutSiteApi.Entities.CurdSnack")
                        .WithOne("Detail")
                        .HasForeignKey("AngularTutSiteApi.Entities.CurdSnackDetail", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
